[package]
name = "tss-sol-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
hex = "0.4.3"
hex-literal = "0.4.1"
#frost-secp256k1 = "0.1.0"
k256 = "0.13.1"
rosetta-client = "0.1.1"
rosetta-config-ethereum = "0.1.0"
rosetta-docker = "0.1.0"
serde_json = "1.0.96"
sha3 = "0.10.7"
tokio = { version = "1.27.0", features = ["full"] }

[patch.crates-io]
rosetta-client = { path = "../chain-connectors/rosetta-client" }
rosetta-config-ethereum = { path = "../chain-connectors/chains/ethereum/config" }
rosetta-docker = { path = "../chain-connectors/rosetta-docker" }
