[package]
name = "frost-evm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.73"
frost-core = { features = ["internals"], git = "https://github.com/zcashfoundation/frost", branch = "main" }
frost-secp256k1 = { git = "https://github.com/zcashfoundation/frost", branch = "main" }
k256 = "0.13.1"
serde = "1.0.183"
sha3 = "0.10.8"
