[package]
name = "frost-evm"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = "0.5.2"
frost-core = { version = "0.2.0", features = ["internals"], git = "https://github.com/dvc94ch/frost", branch = "serde" }
frost-secp256k1 = { version = "0.2.0", git = "https://github.com/dvc94ch/frost", branch = "serde" }
k256 = "0.13.1"
rand_core = "0.6.4"
sha3 = "0.10.7"
